# CircleCI configuration file
version: 2.1

jobs:
  build:
    docker:
     - image: cimg/base:2022.05
    steps:
        #- run: echo "Say hello to YAML!"
      - run:
          name: Clone frontend repository
          command: >-
            GIT_SSH_COMMAND=
            #git clone git@github.com:alex-moreno/commit-bot.git 
	     git clone https://github.com/alex-moreno/commit-bot.git

